image: ubuntu
stages:
  - test
  - build
  - deploy
###################
## Code build
###################
build:
  image: node:16.15.0
  stage: build
  before_script:
    #    - if [ $CI_COMMIT_BRANCH == "dev" ]; then echo "$DEV_ENV" > .env; fi
    #    - if [ $CI_COMMIT_BRANCH == "master" ]; then echo "$PROD_ENV" > .env; fi
    - npm install
  script:
    #    - CI=false npm run build
    - if [ $CI_COMMIT_BRANCH == "dev" ]; then CI=false npm run build:staging; fi
    - if [ $CI_COMMIT_BRANCH == "master" ]; then CI=false npm run build:production; fi
  only:
    refs:
      - dev
      - master
    # rules:
    #   - if: '$CI_COMMIT_BRANCH == "master"'
    #     when: manual
    #   - if: '$CI_COMMIT_BRANCH != "dev"'
    #     when: never
    #   - when: always
  artifacts:
    paths:
      - build/
    expire_in: 1 day
###################
# DEPLOY ARTIFACTS
###################
deploy:
  stage: deploy
  needs:
    - build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git rsync -y )'
    - |
      eval $(ssh-agent -s)
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      chmod 644 ~/.ssh/known_hosts
      if [ $CI_COMMIT_BRANCH == "master" ]; then
           DEST_PATH=$PROD_DEST_PATH;
           HOST=$PROD_HOST
      fi
      if [ $CI_COMMIT_BRANCH == "dev" ]; then
           DEST_PATH=$DEV_DEST_PATH;
           HOST=$DEV_HOST
      fi
  script:
    - rsync -e "ssh -o StrictHostKeyChecking=no" -arvc ./build/ $USER@$HOST:/$DEST_PATH
  only:
    refs:
      - dev
      - master
######################
## CODE QUALITY CHECKS
######################
sonarqube-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - dev