image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy
######################
## BUILD
######################
build:
  image: node:16
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day
######################
## DEPLOY
######################
deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  before_script:
    - AWS_BUCKET="$S3_BUCKET_NAME"
    - DISTRIBUTION_ID="$DISTRIBUTION_ID"
  script:
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 cp ./build s3://$AWS_BUCKET/ --recursive
    - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
